num_motors: 4

id_numbers:
  - 1
  - 2
  - 3
  - 4
  
muscle_K: 
  - 260
  - 250
  - 200
  - 150



muscle_D:
  - 0.1
  - 0.1
  - 0.1
  - 0.1

muscle_M:
  - 1.0
  - 1.0
  - 1.0
  - 1.0

muscle_L:
  - 1.0
  - 1.0
  - 1.0
  - 1.0

muscle_G:
  - 9.81
  - 9.81
  - 9.81
  - 9.81

muscle_refLocation:
  - 0.0
  - 0.0
  - 0.0
  - 0.0